import { Footer } from "@/components/shared/footer"
import CommunityPageClient from "@/components/community/CommunityPageClient"

export default function CommunityPage() {
  return (
    <div className="min-h-screen bg-background flex flex-col">
      <main className="flex-grow container mx-auto px-4 py-12">
        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-6xl font-bold tracking-tight">Community Creations</h1>
          <p className="mt-4 text-lg text-muted-foreground max-w-2xl mx-auto">
            Explore the amazing videos and images generated by the Higgsfield AI community.
          </p>
        </div>
        <CommunityPageClient />
      </main>
      <Footer />
    </div>
  )
}
